site_name: Backstage Playground

theme:
  name: material
  palette: 
      # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode        
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.copy
    - navigation.footer
  font: 
    text: Exo 2
    code: Roboto Mono

docs_dir: docs
# Powers the GitHub links in top bar
repo_url: https://github.com/on-clouds/backstage
repo_name: on-clouds/backstage

# Something?
edit_uri: edit/main/web-docs/

nav:
  - 'Home': 'index.md'

# pip install mkdocs-macros-plugin
# Allows use of variables (see `extras` below)
plugins:
  - macros

extra:
  # when code is updated
  # this var can be removed and
  # we can use {{ site.repo_name }} (see above)
  # instead
  temp_site_url: "on-clouds/backstage"
  social:
    - icon: material/github
      link: https://github.com/on-clouds/backstage
        
