apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-org-config
data:
  org.yaml: |-

    {{- range $i, $group := .Values.backstage.groups }}
    ---
    apiVersion: backstage.io/v1alpha1
    kind: Group
    metadata:
      name: {{ $group.name }}
    spec:
      type: team
      children: {{ $group.children }}
    {{- end }}

    {{- range $i, $user := .Values.backstage.users }}
    ---
    apiVersion: backstage.io/v1alpha1
    kind: User
    metadata:
      name: {{ $user.name }}
    spec:
      memberOf: {{ $user.memberOf }}
    {{- end }}
